### ISSUE TITLE
Develop the Trending section on the Event page

### ISSUE THREAD

**Issue by ariyoaresa** [OSCA-Ado-Ekiti/EventTrakka#1]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by Elijah699** [comment]
@ariyoaresa I can't find a trending section on the event page. Kindly review the figma design and you can also send a screenshot so i can ascertain which area you're working on.

**Comment by ariyoaresa** [comment]
![IMG-20241008-WA0267](https://github.com/user-attachments/assets/05dde5a3-3632-455b-83d9-a9370da7de63)

This is the second section of the event page, just before the upcoming events

**Comment by Elijah699** [comment]
@ariyoaresa You can proceed. I'm sorry about the delay i just needed to confirm where you wanted to work on.

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #17
