### ISSUE TITLE
 Develop the Upcoming Event section on the About us page while also importing the Footer and subscribe section

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/EventTrakka#10]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by nobledeveloper01** [comment]
This has been worked on before

**Comment by OSCA-Ado-Ekiti** [comment]
@nobledeveloper01 Thank you for pointing that out. I will close the issue rightaway
