### ISSUE TITLE
Develop the Upcoming Event section on the About us page 

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/EventTrakka#11]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by Maloney18** [comment]
Assign me to this task

**Comment by nobledeveloper01** [comment]
i have done this before

**Comment by OSCA-Ado-Ekiti** [comment]
@nobledeveloper01 Have you sent a PR for this?
