### ISSUE TITLE
Develop the Hero section of the Event page

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/EventTrakka#14]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by GautamBytes** [comment]
Hey @OSCA-Ado-Ekiti , can you please assign this issue to me and label it as hackatoberfest accepted?

**Comment by Akash-cloud001** [comment]
Hi! 👋

I’d like to take on the task of developing the Hero section of the Event page. I’ll focus on creating a visually appealing design with impactful content. Please assign this issue to me!

Thanks!

**Comment by ariyoaresa** [comment]
I'll love to work on this

**Comment by OSCA-Ado-Ekiti** [comment]
@GautamBytes are you still available to work on this?

**Comment by GautamBytes** [comment]
Hii @OSCA-Ado-Ekiti , yes i can work on this but can you please elaborate a bit like exactly how you want it  and which specific figma slide to refer .Thanks!

**Comment by OSCA-Ado-Ekiti** [comment]
@GautamBytes This is the figma link [here](https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=467-128&node-type=frame&t=BYVwoylWqvVBTemc-0). This is image of what the session looks like

![image](https://github.com/user-attachments/assets/d7d64399-1987-46e7-8053-a259b3de6272)

**Comment by GautamBytes** [comment]
Sure , thanks for assigning , i will do it!

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #21
