### ISSUE TITLE
Develop a responsive signup page using the figma link below

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/EventTrakka#15]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=LaYd43Mtw6Tn6FYp-0

**Comment by Snehalgupta-07** [comment]
Hi! I can do this task can u please assign it to me :)

**Comment by Akash-cloud001** [comment]
Hi there! 👋

I would love to work on this issue. I can develop a fully responsive signup page based on the provided Figma design. Please assign this task to me.

Thank you!

**Comment by nobledeveloper01** [comment]
hi pls assign me to this

**Comment by OSCA-Ado-Ekiti** [comment]
@nobledeveloper01 Kindly proceed with this.

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #22
