### ISSUE TITLE
Enhance the responsiveness of Upcoming section in the About page

### ISSUE THREAD

**Issue by DanielAgbeni** [OSCA-Ado-Ekiti/EventTrakka#16]
The Upcoming Section in the about page isnt responsive to mobile 
this are images to show it isnt responsive 

![image](https://github.com/user-attachments/assets/5c3cacee-cd27-42a0-a7de-09d438ae614f)
![image](https://github.com/user-attachments/assets/c9a62844-1c1d-4151-82a6-c60b8c04be8a)

**Comment by DanielAgbeni** [comment]
Pls assign Me to the Task

**Comment by OSCA-Ado-Ekiti** [comment]
You can work on this @DanielAgbeni

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #18
