### ISSUE TITLE
Clean up of design inconsistencies and proper routing of the whole project

### ISSUE THREAD

**Issue by Maloney18** [OSCA-Ado-Ekiti/EventTrakka#2]
Adjustment of the hero section in the landing page to fit the figma design, addition of the specified font  (poppins) in the figma design to the project, routing all pages properly, some adjustment to the login page design (there is an overlap there), will add some patches to make the design fully responsive (I noticed that the medium screen needs some little fixes too)

**Comment by Maloney18** [comment]
Assign me to this task

**Comment by Elijah699** [comment]
@Maloney18 You can proceed to make those fixes.

**Comment by OSCA-Ado-Ekiti** [comment]
Merged #6
