### ISSUE TITLE
Work on the past event, organizer contact us and footer section page for the community page of Gdsc Eksu

### ISSUE THREAD

**Issue by OSCA-Ado-Ekiti** [OSCA-Ado-Ekiti/EventTrakka#27]
![Screenshot (26)](https://github.com/user-attachments/assets/c2a6d6c9-2afb-431c-a0e6-c440aed30c30)

**Comment by OSCA-Ado-Ekiti** [comment]
https://www.figma.com/design/w1Hoj9ESFonR8tDl5WLedU/Event-Management?node-id=0-1&node-type=canvas&t=I68O6UxtKMLgmDE4-0

**Comment by sumedhakoranga** [comment]
Hi, I have started working on this issue. Please assign it to me. Thanks.

**Comment by sumedhakoranga** [comment]
Hi, I have submitted a [pull request ](https://github.com/OSCA-Ado-Ekiti/EventTrakka/pull/28). Could you please assign the issue to me and review the PR? Thanks!

**Comment by OSCA-Ado-Ekiti** [comment]
Sure, thank you for contributing @sumedhakoranga
