### ISSUE TITLE
Remove navbar from signup-page and make the hero section of the about-page mobile responsive

### ISSUE THREAD

**Issue by Maloney18** [OSCA-Ado-Ekiti/EventTrakka#31]
![Screenshot (21)](https://github.com/user-attachments/assets/5814b2c5-2f1b-4bf1-ac04-c4ee30b109c8)

![Screenshot (23)](https://github.com/user-attachments/assets/dc1d2b6b-90b9-4d32-99fc-ccaa28d9a844)

**Comment by Maloney18** [comment]
assign me to this task

**Comment by OSCA-Ado-Ekiti** [comment]
@Maloney18 this is the deployed URL of the website, https://event-trakka.vercel.app . If you visit the URL the login doesn't have a navbar and I think we need it because if it's not there people can't easily navigate back to another page.

So you need to adjust the title of your issue to Add Navbar

**Comment by Maloney18** [comment]
So I'm guessing this design will be there pending the time the API is being developed.

**Comment by Elijah699** [comment]
@Maloney18 I will close this now, you've attended to it in your last PR
